/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/signup/": {
    /** Create new user account */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SignupRequest"];
        };
      };
      responses: {
        /** @description Account successfully created */
        200: {
          content: never;
        };
        /** @description Credentials invalid! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/fobs/": {
    /** Get a group of Fobs (query) */
    get: {
      parameters: {
        query?: {
          /** @description Filter Fobs by type (fountain or bathroom) */
          type?: "fountain" | "bathroom";
          /** @description Latitude to fetch Fobs around. If provided, must provide longitude! */
          latitude?: number;
          /** @description Longitude to fetch Fobs around. If provided, must also provide latitude! */
          longitude?: number;
          /** @description Radius to fetch Fobs within (in meters) */
          radius?: number;
          /** @description ID of user that created the Fob(s) */
          user_id?: string;
          /** @description Filter fountains to those created on or after this date.  Unix epoch milliseconds timestamp. */
          from_date?: number;
          /** @description Filter fountains to those created before or on this date.  Unix epoch milliseconds timestamp. */
          to_date?: number;
        };
      };
      responses: {
        /** @description Successful query. Return array of Fobs. */
        200: {
          content: {
            "application/json": components["schemas"]["Fob"][];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Add a Fob */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["FobCreationDetails"];
        };
      };
      responses: {
        /** @description Successfully added Fob! */
        201: {
          content: {
            "application/json": components["schemas"]["Fob"];
          };
        };
        /** @description Malformed request! Missing some information or not in the right format. */
        400: {
          content: never;
        };
        /** @description Access token incorrect / insufficient / expired! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/auth/refresh": {
    /** Auth token refresh */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthRefreshRequest"];
        };
      };
      responses: {
        /** @description Successful refresh request, grant new tokens */
        200: {
          content: {
            "application/json": components["schemas"]["AuthSuccessResponse"];
          };
        };
        /** @description Request is missing required information or is incorrectly formatted */
        400: {
          content: never;
        };
        /** @description Credentials incorrect or refresh token expired! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/auth/": {
    /** Simple endpoint to check if auth token / user account is valid */
    get: {
      responses: {
        /** @description Auth token / user account OK */
        200: {
          content: never;
        };
        /** @description Malformed request (missing access token?) */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed (token invalid or account not found) */
        401: {
          content: never;
        };
      };
    };
    /** Password authentication */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthRequest"];
        };
      };
      responses: {
        /** @description Successful auth request, return tokens and token information */
        200: {
          content: {
            "application/json": components["schemas"]["AuthSuccessResponse"];
          };
        };
        /** @description Request is missing required information or is incorrectly formatted */
        400: {
          content: never;
        };
        /** @description User credentials are incorrect */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/auth/password-reset/request": {
    /** Request password reset */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["PasswordResetRequest"];
        };
      };
      responses: {
        /** @description Password reset email sent if account exists */
        200: {
          content: {
            "application/json": components["schemas"]["PasswordResetResponse"];
          };
        };
        /** @description Request is missing required information or is incorrectly formatted */
        400: {
          content: never;
        };
      };
    };
  };
  "/api/auth/password-reset/reset": {
    /** Reset password */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["PasswordResetResetRequest"];
        };
      };
      responses: {
        /** @description Password reset successful, returns auth tokens */
        200: {
          content: {
            "application/json": components["schemas"]["AuthSuccessResponse"];
          };
        };
        /** @description Request is missing required information, passwords don't match, or token invalid */
        400: {
          content: never;
        };
      };
    };
  };
  "/api/profiles/{username}": {
    /** Get a profile by username */
    get: {
      parameters: {
        path: {
          username: string;
        };
      };
      responses: {
        /** @description Successfully fetched user profile */
        200: {
          content: {
            "application/json": components["schemas"]["Profile"];
          };
        };
        /** @description Malformed request (missing username?) */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed (access token invalid, or maybe not allowed to view this profile?) */
        403: {
          content: never;
        };
        /** @description User with provided username not found! */
        404: {
          content: never;
        };
      };
    };
    /** Update user profile by username */
    put: {
      parameters: {
        path: {
          username: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      responses: {
        /** @description Successfully updated user profile! */
        200: {
          content: {
            "application/json": components["schemas"]["Profile"];
          };
        };
        /** @description Malformed request! */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed! */
        401: {
          content: never;
        };
        /** @description Could not find user with ID */
        404: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        username: string;
      };
    };
  };
  "/api/fobs/{id}/pictures": {
    /** Get pictures for a Fob */
    get: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
        };
      };
      responses: {
        /** @description Successful pictures request */
        200: {
          content: {
            "application/json": components["schemas"]["PictureSignedUrl"][];
          };
        };
        /** @description Malformed request (may be missing required parameters) */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Fob with given ID does not exist! */
        404: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        /** @description ID of the Fob */
        id: string;
      };
    };
  };
  "/api/fobs/{id}/pictures/upload": {
    /** Get picture upload link for a Fob */
    get: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
        };
      };
      responses: {
        /** @description Successful picture upload URL request */
        200: {
          content: {
            "application/json": components["schemas"]["PictureSignedUrl"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Fob does not exist! */
        404: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        /** @description ID of the Fob */
        id: string;
      };
    };
  };
  "/api/pictures/{id}": {
    /** Get a specific picture by ID */
    get: {
      parameters: {
        path: {
          /** @description ID of the picture */
          id: string;
        };
      };
      responses: {
        /** @description Successful request, return picture URL */
        200: {
          content: {
            "application/json": components["schemas"]["PictureSignedUrl"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Picture with provided ID not found! */
        404: {
          content: never;
        };
      };
    };
    /** Update the pending property of a Picture */
    put: {
      parameters: {
        path: {
          /** @description ID of the picture */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** @description Updated pending status of the picture */
            pending: boolean;
          };
        };
      };
      responses: {
        /** @description Successfully updated the picture's pending status */
        200: {
          content: never;
        };
        /** @description Malformed request (missing or invalid ID or body) */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Picture with provided ID not found! */
        404: {
          content: never;
        };
      };
    };
    /** Delete a specific picture by ID */
    delete: {
      parameters: {
        path: {
          /** @description ID of the picture */
          id: string;
        };
      };
      responses: {
        /** @description Successfully deleted the picture */
        200: {
          content: never;
        };
        /** @description Malformed request (missing or invalid ID) */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Picture with provided ID not found! */
        404: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        /** @description ID of the picture */
        id: string;
      };
    };
  };
  "/api/fobs/{id}/ratings": {
    /** Get ratings for a particular Fob */
    get: {
      parameters: {
        query?: {
          /** @description Optional pagination: Size of pages to fetch (number of ratings per page) */
          page_size?: number;
          /** @description Optional pagination: Offset of page to fetch (default is 0, max is 100) */
          page_offset?: number;
        };
        path: {
          /** @description ID of the Fob */
          id: string;
        };
      };
      responses: {
        /** @description Successful query. Return array of Fob ratings. */
        200: {
          content: {
            "application/json": components["schemas"]["Rating"][];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Add a Fob rating */
    post: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["FountainRatingDetails"] | components["schemas"]["BathroomRatingDetails"];
        };
      };
      responses: {
        /** @description Successfully added Fob rating! */
        201: {
          content: {
            "application/json": components["schemas"]["Rating"];
          };
        };
        /** @description Malformed request! Missing some information or not in the right format. */
        400: {
          content: never;
        };
        /** @description Access token incorrect / insufficient / expired! */
        401: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        /** @description ID of the Fob */
        id: string;
      };
    };
  };
  "/api/fobs/{id}/ratings/{ratingId}": {
    /** Get a specific rating for a Fob */
    get: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
          /** @description ID of the rating */
          ratingId: string;
        };
      };
      responses: {
        /** @description Successful request, return Fob rating */
        200: {
          content: {
            "application/json": components["schemas"]["Rating"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Rating with provided ID not found! */
        404: {
          content: never;
        };
      };
    };
    /** Update a specific rating for a Fob */
    put: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
          /** @description ID of the rating */
          ratingId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Rating"];
        };
      };
      responses: {
        /** @description Fob rating successfully updated! */
        200: {
          content: {
            "application/json": components["schemas"]["Rating"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Rating with provided ID not found! */
        404: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        /** @description ID of the Fob */
        id: string;
        /** @description ID of the rating */
        ratingId: string;
      };
    };
  };
  "/api/fobs/{id}": {
    /** Get Fob by ID */
    get: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
        };
      };
      responses: {
        /** @description Successful request, return Fob. */
        200: {
          content: {
            "application/json": components["schemas"]["Fob"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Invalid auth */
        401: {
          content: never;
        };
        /** @description Fob not found */
        404: {
          content: never;
        };
      };
    };
    /** Update Fob info for a particular Fob */
    put: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Fob"];
        };
      };
      responses: {
        /** @description Fob successfully updated! */
        200: {
          content: {
            "application/json": components["schemas"]["Fob"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Insufficient auth */
        403: {
          content: never;
        };
        /** @description Fob not found */
        404: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        /** @description ID of the Fob */
        id: string;
      };
    };
  };
  "/api/fobs/{id}/details": {
    /** Get detailed information about a Fob */
    get: {
      parameters: {
        path: {
          /** @description ID of the Fob */
          id: string;
        };
      };
      responses: {
        /** @description Successfully retrieved Fob details */
        200: {
          content: {
            "application/json": components["schemas"]["FobWithDetails"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Fob with provided ID not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/": {
    /** Generic endpoint */
    get: {
      responses: {
        /** @description Server OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/profiles/{username}/contributions": {
    /**
     * Get user contributions for specified user
     * @description Uses an optimized database query to get user created fountains, bathrooms, ratings, and pictures. All contributions by that user basically.
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit query to contributions on and after this date.  Unix epoch milliseconds timestamp. */
          from_date?: number;
          /** @description Limit query to contributions up to and on this date.  Unix epoch milliseconds timestamp. */
          to_date?: number;
        };
        path: {
          username: string;
        };
      };
      responses: {
        /** @description Request successful. Returns user contributions. */
        200: {
          content: {
            "application/json": components["schemas"]["UserContributions"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed (access token invalid, or maybe not allowed to view this profile?) */
        401: {
          content: never;
        };
        /** @description User not found */
        404: {
          content: never;
        };
      };
    };
    parameters: {
      path: {
        username: string;
      };
    };
  };
  "/api/me/contributions": {
    /**
     * Get contributions for the authenticated user
     * @description Uses an optimized database query to get the authenticated user's created fountains, bathrooms, ratings, and pictures without requiring the username in the path.
     */
    get: {
      parameters: {
        query?: {
          /** @description Limit query to contributions on and after this date. Unix epoch milliseconds timestamp. */
          from_date?: number;
          /** @description Limit query to contributions up to and on this date. Unix epoch milliseconds timestamp. */
          to_date?: number;
        };
      };
      responses: {
        /** @description Request successful. Returns authenticated user's contributions. */
        200: {
          content: {
            "application/json": components["schemas"]["UserContributions"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed (access token invalid) */
        401: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @example {
     *   "username": "some text",
     *   "email": "some text",
     *   "profile": {
     *     "full_name": "some text",
     *     "picture_link": "some text"
     *   },
     *   "id": "some text",
     *   "created_at": 12,
     *   "updated_at": 3
     * }
     */
    User: {
      /** @description Username of user */
      username: string;
      /** @description Email address of user */
      email: string;
      profile: components["schemas"]["Profile"];
      /** @description Unique user id (not technically necessary but helpful) */
      id: string;
      /** @description Created timestamp.  Unix epoch milliseconds. */
      created_at?: number;
      /** @description Updated timestamp.  Unix epoch milliseconds. */
      updated_at?: number;
    };
    /**
     * @example {
     *   "full_name": "some text",
     *   "picture_link": "some text"
     * }
     */
    Profile: {
      /** @description Full name of user */
      full_name: string;
      /** @description Link to profile photo */
      picture_link: string;
    };
    /**
     * @description Rating for a Fob
     * @example {
     *   "id": "rating123",
     *   "fob_id": "fob456",
     *   "user_id": "user789",
     *   "details": {
     *     "pressure": 5,
     *     "taste": 4,
     *     "temperature": 3
     *   },
     *   "created_at": 1672531200000,
     *   "updated_at": 1672617600000
     * }
     */
    Rating: {
      /** @description Unique ID of the rating */
      id: string;
      /** @description ID of the Fob being rated */
      fob_id: string;
      /** @description ID of the user who created the rating */
      user_id: string;
      /** @description Details of the rating, specific to the type of Fob */
      details: components["schemas"]["FountainRatingDetails"] | components["schemas"]["BathroomRatingDetails"];
      /** @description Created timestamp. Unix epoch milliseconds. */
      created_at?: number;
      /** @description Updated timestamp. Unix epoch milliseconds. */
      updated_at?: number;
    };
    /**
     * @description Details of a rating including the user who created it
     * @example {
     *   "rating": {
     *     "id": "rating123",
     *     "fob_id": "fob456",
     *     "user_id": "user789",
     *     "details": {
     *       "pressure": 5,
     *       "taste": 4,
     *       "temperature": 3
     *     },
     *     "created_at": 1672531200000,
     *     "updated_at": 1672617600000
     *   },
     *   "user": {
     *     "id": "user789",
     *     "username": "exampleUser",
     *     "email": "example@example.com",
     *     "profile": {
     *       "full_name": "Example User",
     *       "picture_link": "https://example.com/profile.jpg"
     *     },
     *     "created_at": 1672531200000,
     *     "updated_at": 1672617600000
     *   }
     * }
     */
    RatingWithDetails: {
      rating: components["schemas"]["Rating"];
      user: components["schemas"]["User"];
    };
    /**
     * @example {
     *   "id": "some text",
     *   "fob_id": "some text",
     *   "url": "some text",
     *   "user_id": "some text",
     *   "created_at": 9,
     *   "updated_at": 86
     * }
     */
    Picture: {
      /** @description Unique ID of picture */
      id: string;
      /** @description Fountain or bathroom ID picture is for */
      fob_id: string;
      /** @description Url for picture */
      url: string;
      /** @description ID of user that created the picture. */
      user_id: string;
      /** @description Pending status of the picture (true or false). I.e., whether or not the picture is fully uploaded to S3 yet */
      pending?: boolean;
      /** @description Created timestamp.  Unix epoch milliseconds. */
      created_at?: number;
      /** @description Updated timestamp.  Unix epoch milliseconds. */
      updated_at?: number;
    };
    /**
     * @example {
     *   "picture_id": "some text",
     *   "signed_url": "some text",
     *   "expires": 174857296748
     * }
     */
    PictureSignedUrl: {
      /** @description ID of the picture */
      picture_id: string;
      /** @description Signed URL for picture */
      signed_url: string;
      /** @description Expiration time of the signed URL in Unix epoch milliseconds */
      expires: number;
    };
    /**
     * @description Set of login credentials
     * @example {
     *   "email": "some text",
     *   "password": "some text"
     * }
     */
    UserCredentials: {
      /** @description Email address of user */
      email: string;
      /** @description User's password */
      password: string;
    };
    /**
     * @description Identify a unique location (longitude and latitude)
     * @example {
     *   "longitude": 38.13,
     *   "latitude": 35.74
     * }
     */
    Location: {
      /** @description Longitude of location */
      longitude: number;
      /** @description Latitude of location */
      latitude: number;
    };
    /**
     * @description Information needed for signup request
     * @example {
     *   "username": "some text",
     *   "user_credentials": {
     *     "email": "some text",
     *     "password": "some text"
     *   }
     * }
     */
    SignupRequest: {
      /** @description New username for new user */
      username: string;
      user_credentials: components["schemas"]["UserCredentials"];
    };
    /** @description Fountain or bathroom information */
    Fob: {
      /** @description Unique ID of fob */
      id: string;
      /** @description Info about the Fob, can be either FountainInfo or BathroomInfo */
      info: components["schemas"]["FountainInfo"] | components["schemas"]["BathroomInfo"];
      /** @description Created timestamp.  Unix epoch milliseconds. */
      created_at?: number;
      /** @description Updated timestamp.  Unix epoch milliseconds. */
      updated_at?: number;
      /** @description Name of fob */
      name: string;
      location: components["schemas"]["Location"];
      /** @description ID of user who created the fob */
      user_id: string;
      /** @description Average rating of the fob */
      average_rating?: number | null;
    };
    /**
     * @example {
     *   "bottle_filler": true
     * }
     */
    FountainInfo: {
      /** @description Whether or not the fountain features a dedicated bottle filler */
      bottle_filler: boolean;
    };
    /**
     * @example {
     *   "gender": "some text",
     *   "sanitary_products": true,
     *   "baby_changer": true
     * }
     */
    BathroomInfo: {
      /** @description Gender/sex of bathroom */
      gender: string;
      /** @description Whether or not bathroom has sanitary products available (such as tampons and pads) */
      sanitary_products: boolean;
      /** @description Whether or not bathroom has a baby changer available */
      baby_changer: boolean;
    };
    /**
     * @description Actual details of bathroom rating
     * @example {
     *   "cleanliness": 3,
     *   "decor": 1,
     *   "drying": 2,
     *   "privacy": 3,
     *   "washing": 5
     * }
     */
    BathroomRatingDetails: {
      /** @description Cleanliness rating of bathroom (1-5) */
      cleanliness: number;
      /** @description Decor rating of bathroom (1-5) */
      decor: number;
      /** @description Drying rating of bathroom (1-5) */
      drying: number;
      /** @description Privacy rating of bathroom (1-5) */
      privacy: number;
      /** @description Washing rating of bathroom (1-5) */
      washing: number;
    };
    /**
     * @description Details of fountain rating
     * @example {
     *   "pressure": 5,
     *   "taste": 4,
     *   "temperature": 1
     * }
     */
    FountainRatingDetails: {
      /** @description Pressure rating for fountain (1-5) */
      pressure: number;
      /** @description Taste rating for fountain (1-5) */
      taste: number;
      /** @description Temperature rating for fountain (1-5) */
      temperature: number;
    };
    /**
     * @description Tokens and token information returned after successful auth request
     * @example {
     *   "access_token": "some text",
     *   "refresh_token": "some text",
     *   "token_type": "some text",
     *   "expires": 12,
     *   "username": "some text"
     * }
     */
    AuthSuccessResponse: {
      /** @description Access token for user */
      access_token: string;
      /** @description Token to use to get a new token once access_token expires */
      refresh_token: string;
      /** @description Type of token (will be "Bearer") */
      token_type: string;
      /** @description Number of seconds that access_token is valid for */
      expires: number;
      /** @description Username of authenticated user */
      username: string;
    };
    /**
     * @description Request format for refreshing auth access token
     * @example {
     *   "refresh_token": "some text",
     *   "expired_token": "some text"
     * }
     */
    AuthRefreshRequest: {
      /** @description Refresh token */
      refresh_token: string;
      /** @description Expired access token */
      expired_token: string;
    };
    /**
     * @description Body of POST request for authentication
     * @example {
     *   "user_credentials": {
     *     "email": "some text",
     *     "password": "some text"
     *   }
     * }
     */
    AuthRequest: {
      user_credentials: components["schemas"]["UserCredentials"];
    };
    /**
     * @description Request to send password reset email
     * @example {
     *   "email": "user@example.com"
     * }
     */
    PasswordResetRequest: {
      /** @description Email address of the account */
      email: string;
    };
    /**
     * @description Response for password reset request
     * @example {
     *   "message": "If an account exists with that email, a password reset email has been sent."
     * }
     */
    PasswordResetResponse: {
      /** @description Confirmation message */
      message: string;
    };
    /**
     * @description Request to reset password
     * @example {
     *   "token": "abc123...",
     *   "new_password": "newpassword",
     *   "confirm_password": "newpassword"
     * }
     */
    PasswordResetResetRequest: {
      /** @description Password reset token */
      token: string;
      /** @description New password */
      new_password: string;
      /** @description Confirm new password */
      confirm_password: string;
    };
    /**
     * @description Summary of user contributions
     * @example {
     *   "fobs": [
     *     {
     *       "id": "some text",
     *       "info": {
     *         "bottle_filler": true
     *       },
     *       "user_id": "some text",
     *       "created_at": 71,
     *       "updated_at": 64,
     *       "name": "some text",
     *       "location": {
     *         "longitude": 87.62,
     *         "latitude": 97.01
     *       }
     *     },
     *     {
     *       "id": "some text",
     *       "info": {
     *         "bottle_filler": true
     *       },
     *       "user_id": "some text",
     *       "created_at": 79,
     *       "updated_at": 56,
     *       "name": "some text",
     *       "location": {
     *         "longitude": 87.37,
     *         "latitude": 8.19
     *       }
     *     }
     *   ],
     *   "ratings": [
     *     {
     *       "id": "some text",
     *       "fob_id": "some text",
     *       "user_id": "some text",
     *       "details": {
     *         "cleanliness": 2,
     *         "decor": 7,
     *         "drying": 42,
     *         "privacy": 65,
     *         "washing": 96
     *       },
     *       "created_at": 72,
     *       "updated_at": 44
     *     },
     *     {
     *       "id": "some text",
     *       "fob_id": "some text",
     *       "user_id": "some text",
     *       "details": {
     *         "cleanliness": 74,
     *         "decor": 49,
     *         "drying": 13,
     *         "privacy": 7,
     *         "washing": 65
     *       },
     *       "created_at": 83,
     *       "updated_at": 20
     *     }
     *   ],
     *   "pictures": [
     *     {
     *       "id": "some text",
     *       "fob_id": "some text",
     *       "url": "some text",
     *       "user_id": "some text",
     *       "created_at": 65,
     *       "updated_at": 97
     *     },
     *     {
     *       "id": "some text",
     *       "fob_id": "some text",
     *       "url": "some text",
     *       "user_id": "some text",
     *       "created_at": 89,
     *       "updated_at": 22
     *     }
     *   ]
     * }
     */
    UserContributions: {
      /** @description Fobs created by the user */
      fobs: components["schemas"]["Fob"][];
      /** @description Fob ratings created by user */
      ratings: components["schemas"]["Rating"][];
      /** @description Pictures created by user */
      pictures: components["schemas"]["Picture"][];
    };
    /**
     * @description Information necessary to create a Fob
     * @example {
     *   "name": "Example Fob",
     *   "location": {
     *     "longitude": 25.86,
     *     "latitude": 2.67
     *   },
     *   "info": {
     *     "bottle_filler": true
     *   }
     * }
     */
    FobCreationDetails: {
      /**
       * @description Type of the Fob
       * @enum {unknown}
       */
      type: "fountain" | "bathroom";
      /** @description Name of the Fob */
      name: string;
      location: components["schemas"]["Location"];
      /** @description Details about the Fob */
      info: components["schemas"]["FountainInfo"] | components["schemas"]["BathroomInfo"];
    };
    /**
     * @description Details of a Fob including its pictures and ratings
     * @example {
     *   "fob": {
     *     "id": "fob123",
     *     "info": {
     *       "bottle_filler": true
     *     },
     *     "user_id": "user456",
     *     "created_at": 1672531200000,
     *     "updated_at": 1672617600000,
     *     "name": "Example Fob",
     *     "location": {
     *       "longitude": 25.86,
     *       "latitude": 2.67
     *     }
     *   },
     *   "user": {
     *     "username": "some text",
     *     "email": "some text",
     *     "profile": {
     *       "full_name": "some text",
     *       "picture_link": "some text"
     *     },
     *     "id": "some text",
     *     "created_at": 1672531200000,
     *     "updated_at": 1672531200000
     *   },
     *   "pictures": [
     *     {
     *       "id": "pic123",
     *       "fob_id": "fob123",
     *       "url": "https://example.com/pic1.jpg",
     *       "user_id": "user789",
     *       "created_at": 1672531200000,
     *       "updated_at": 1672617600000
     *     },
     *     {
     *       "id": "pic124",
     *       "fob_id": "fob123",
     *       "url": "https://example.com/pic2.jpg",
     *       "user_id": "user789",
     *       "created_at": 1672531200000,
     *       "updated_at": 1672617600000
     *     }
     *   ],
     *   "ratingsWithDetails": [
     *     {
     *       "rating": {
     *         "id": "rating123",
     *         "fob_id": "fob123",
     *         "user_id": "user789",
     *         "details": {
     *           "pressure": 5,
     *           "taste": 4,
     *           "temperature": 3
     *         },
     *         "created_at": 1672531200000,
     *         "updated_at": 1672617600000
     *       },
     *       "user": {
     *         "id": "user789",
     *         "username": "exampleUser1",
     *         "email": "example1@example.com",
     *         "profile": {
     *           "full_name": "Example User 1",
     *           "picture_link": "https://example.com/profile1.jpg"
     *         },
     *         "created_at": 1672531200000,
     *         "updated_at": 1672617600000
     *       }
     *     },
     *     {
     *       "rating": {
     *         "id": "rating124",
     *         "fob_id": "fob123",
     *         "user_id": "user456",
     *         "details": {
     *           "pressure": 5,
     *           "taste": 4,
     *           "temperature": 3
     *         },
     *         "created_at": 1672531200000,
     *         "updated_at": 1672617600000
     *       },
     *       "user": {
     *         "id": "user456",
     *         "username": "exampleUser2",
     *         "email": "example2@example.com",
     *         "profile": {
     *           "full_name": "Example User 2",
     *           "picture_link": "https://example.com/profile2.jpg"
     *         },
     *         "created_at": 1672531200000,
     *         "updated_at": 1672617600000
     *       }
     *     }
     *   ]
     * }
     */
    FobWithDetails: {
      fob: components["schemas"]["Fob"];
      user: components["schemas"]["User"];
      /** @description Array of pictures associated with the Fob */
      pictures: components["schemas"]["Picture"][];
      /** @description Array of ratings (with details) associated with the Fob */
      ratingsWithDetails: components["schemas"]["RatingWithDetails"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
