/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/signup": {
    /** Create new user account */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SignupRequest"];
        };
      };
      responses: {
        /** @description Account successfully created */
        200: {
          content: never;
        };
        /** @description Credentials invalid! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/fountains": {
    /** Get a group of fountains (query) or a certain fountain (by ID) */
    get: {
      parameters: {
        query?: {
          /**
           * @description ID of fountain to fetch.
           * Overrides all other query parameters!
           */
          id?: string;
          /**
           * @description Longitude to fetch fountains around.
           * If provided, must also provide latitude!
           */
          longitude?: number;
          /**
           * @description Latitude to fetch fountains around.
           * If provided, must provide longitude!
           */
          latitude?: number;
          /** @description Filter fountains by bottle_filler property */
          bottle_filler?: boolean;
          /** @description Radius to fetch fountains within */
          radius?: number;
        };
      };
      responses: {
        /** @description Successful query.  Return array of fountains. */
        200: {
          content: {
            "application/json": components["schemas"]["Fountain"][];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed! */
        403: {
          content: never;
        };
      };
    };
    /** Update fountain info for a particular fountain */
    put: {
      parameters: {
        query: {
          /** @description ID of fountain to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["FountainInfo"];
        };
      };
      responses: {
        /** @description Fountain successfully updated! */
        200: {
          content: {
            "application/json": components["schemas"]["Fountain"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Add a fountain */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["FountainInfo"];
        };
      };
      responses: {
        /** @description Successfully added fountain! */
        201: {
          headers: {
            Location?: string;
          };
          content: {
            "application/json": components["schemas"]["Fountain"];
          };
        };
        /** @description Malformed request! Missing some information or not in right format. */
        400: {
          content: never;
        };
        /** @description Access token incorrect / insufficient / expired! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/bathrooms": {
    /** Get a group of bathrooms (query) or a certain bathroom (by ID) */
    get: {
      parameters: {
        query?: {
          /**
           * @description ID of bathroom to fetch.
           * Overrides all other query parameters!
           */
          id?: string;
          /**
           * @description Longitude to fetch bathrooms around.
           * If provided, must also provide latitude!
           */
          longitude?: number;
          /**
           * @description Latitude to fetch bathrooms around.
           * If provided, must provide longitude!
           */
          latitude?: number;
          /** @description Radius to fetch bathrooms within */
          radius?: number;
          /** @description Filter bathrooms by baby_changer property */
          baby_changer?: boolean;
          /** @description Filter bathrooms by gender property */
          gender?: string;
          /** @description Filter bathrooms by sanitary_products property */
          sanitary_products?: boolean;
        };
      };
      responses: {
        /** @description Successful query.  Return array of bathrooms. */
        200: {
          content: {
            "application/json": components["schemas"]["Bathroom"][];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Update bathroom info for a particular bathroom */
    put: {
      parameters: {
        query: {
          /** @description ID of bathroom to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BathroomInfo"];
        };
      };
      responses: {
        /** @description Bathroom successfully updated! */
        200: {
          content: {
            "application/json": components["schemas"]["Bathroom"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Add a bathroom */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["BathroomInfo"];
        };
      };
      responses: {
        /** @description Successfully added bathroom! */
        201: {
          headers: {
            Location?: string;
          };
          content: {
            "application/json": components["schemas"]["Bathroom"];
          };
        };
        /** @description Malformed request! Missing some information or not in right format. */
        400: {
          content: never;
        };
        /** @description Access token incorrect / insufficient / expired! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/bathrooms/ratings": {
    /** Get ratings for a particular bathroom */
    get: {
      parameters: {
        query: {
          /** @description ID of bathroom to fetch ratings for */
          id: string;
          /** @description Optional pagination: Size of pages to fetch (number of ratings per page) */
          page_size?: number;
          /** @description Optional pagination: Offset of page to fetch (default is 0, max is 100) */
          page_offset?: number;
        };
      };
      responses: {
        /** @description Successful query.  Return array of bathroom ratings. */
        200: {
          content: {
            "application/json": components["schemas"]["BathroomRating"][];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Update bathroom rating */
    put: {
      parameters: {
        query: {
          /** @description ID of bathroom rating to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BathroomRatingDetails"];
        };
      };
      responses: {
        /** @description Bathroom rating successfully updated! */
        200: {
          content: {
            "application/json": components["schemas"]["BathroomRating"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Add a bathroom rating */
    post: {
      parameters: {
        query: {
          /** @description ID of bathroom to add rating to */
          bathroom_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["BathroomRatingDetails"];
        };
      };
      responses: {
        /** @description Successfully added bathroom rating! */
        201: {
          headers: {
            Location?: string;
          };
          content: {
            "application/json": components["schemas"]["BathroomRating"];
          };
        };
        /** @description Malformed request! Missing some information or not in right format. */
        400: {
          content: never;
        };
        /** @description Access token incorrect / insufficient / expired! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/fountains/ratings": {
    /** Get ratings for a particular fountain */
    get: {
      parameters: {
        query: {
          /** @description ID of fountain to fetch ratings for */
          id: string;
          /** @description Optional pagination: Size of pages to fetch (number of ratings per page) */
          page_size?: number;
          /** @description Optional pagination: Offset of page to fetch (default is 0, max is 100) */
          page_offset?: number;
        };
      };
      responses: {
        /** @description Successful query.  Return array of fountain ratings. */
        200: {
          content: {
            "application/json": components["schemas"]["FountainRating"][];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Update fountain rating */
    put: {
      parameters: {
        query: {
          /** @description ID of fountain rating to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["FountainRatingDetails"];
        };
      };
      responses: {
        /** @description Fountain rating successfully updated! */
        200: {
          content: {
            "application/json": components["schemas"]["FountainRating"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
        /** @description Authentication failed */
        403: {
          content: never;
        };
      };
    };
    /** Add a fountain rating */
    post: {
      parameters: {
        query: {
          /** @description ID of fountain to add rating to */
          fountain_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["FountainRatingDetails"];
        };
      };
      responses: {
        /** @description Successfully added fountain rating! */
        201: {
          headers: {
            Location?: string;
          };
          content: {
            "application/json": components["schemas"]["FountainRating"];
          };
        };
        /** @description Malformed request! Missing some information or not in right format. */
        400: {
          content: never;
        };
        /** @description Access token incorrect / insufficient / expired! */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/bathrooms/pictures": {
    /**
     * Get bathroom photos
     * @description Fetches all if no offset provided.  Otherwise fetches just that photo.
     */
    get: {
      parameters: {
        query: {
          /** @description Offset of photo to fetch (first picture is 0) */
          offset?: number;
          /** @description ID of bathroom to fetch pictures for */
          bathroom_id: string;
        };
      };
      responses: {
        /** @description Successful photo link request */
        200: {
          content: {
            "application/json": components["schemas"]["Picture"];
          };
        };
        /** @description Malformed request (may be missing required parameters) */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Picture of bathroom with provided offset does not exist! */
        404: {
          content: never;
        };
      };
    };
    /** Add bathroom picture (link only, file hosting will have to be handled separately) */
    post: {
      parameters: {
        query: {
          /** @description ID of bathroom to add photo for */
          bathroom_id: string;
        };
      };
      /** @description Picture link */
      requestBody: {
        content: {
          "application/json": string;
        };
      };
      responses: {
        /** @description Successfully added picture! */
        201: {
          headers: {
            Location?: string;
          };
          content: {
            "application/json": components["schemas"]["Picture"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
      };
    };
    /** Delete a bathroom picture */
    delete: {
      parameters: {
        query: {
          /** @description ID of picture to remove */
          id: string;
        };
      };
      responses: {
        /** @description Successfully removed picture! */
        200: {
          content: never;
        };
        /** @description Malformed request (missing ID?) */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed! */
        403: {
          content: never;
        };
        /** @description Picture with provided ID not found! */
        404: {
          content: never;
        };
      };
    };
  };
  "/api/fountains/pictures": {
    /**
     * Get fountain photos
     * @description Fetches all if no offset provided.  Otherwise fetches just that photo.
     */
    get: {
      parameters: {
        query: {
          /** @description Offset of photo to fetch (first picture is 0) */
          offset?: number;
          /** @description ID of fountain to fetch pictures for */
          fountain_id: string;
        };
      };
      responses: {
        /** @description Successful photo link request */
        200: {
          content: {
            "application/json": components["schemas"]["Picture"];
          };
        };
        /** @description Malformed request (may be missing required parameters) */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
        /** @description Picture of fountain with provided offset does not exist! */
        404: {
          content: never;
        };
      };
    };
    /** Add fountain picture (link only, file hosting will have to be handled separately) */
    post: {
      parameters: {
        query: {
          /** @description ID of fountain to add photo for */
          fountain_id: string;
        };
      };
      /** @description Picture link */
      requestBody: {
        content: {
          "application/json": string;
        };
      };
      responses: {
        /** @description Successfully added picture! */
        201: {
          headers: {
            Location?: string;
          };
          content: {
            "application/json": components["schemas"]["Picture"];
          };
        };
        /** @description Malformed request */
        400: {
          content: never;
        };
        /** @description Authentication/authorization failed */
        401: {
          content: never;
        };
      };
    };
    /** Delete a fountain picture */
    delete: {
      parameters: {
        query: {
          /** @description ID of picture to remove */
          id: string;
        };
      };
      responses: {
        /** @description Successfully removed picture! */
        200: {
          content: never;
        };
        /** @description Malformed request (missing ID?) */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed! */
        403: {
          content: never;
        };
        /** @description Picture with provided ID not found! */
        404: {
          content: never;
        };
      };
    };
  };
  "/api/profiles": {
    /** Get a profile by username */
    get: {
      parameters: {
        query: {
          /** @description Username of user to fetch profile for */
          username: string;
        };
      };
      responses: {
        /** @description Successfully fetched user profile */
        200: {
          content: {
            "application/json": components["schemas"]["UserProfile"];
          };
        };
        /** @description Malformed request (missing username?) */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed (access token invalid, or maybe not allowed to view this profile?) */
        403: {
          content: never;
        };
        /** @description User with provided username not found! */
        404: {
          content: never;
        };
      };
    };
    /** Update user profile by user ID */
    put: {
      parameters: {
        query: {
          /** @description ID of user whose profile to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
      responses: {
        /** @description Successfully updated user profile! */
        200: {
          content: never;
        };
        /** @description Malformed request! */
        400: {
          content: never;
        };
        /** @description Authorization/authentication failed! */
        401: {
          content: never;
        };
        /** @description Could not find user with ID */
        404: {
          content: never;
        };
      };
    };
  };
  "/api/auth": {
    /** Password authentication */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthRequest"];
        };
      };
      responses: {
        /** @description Successful auth request, return tokens and token information */
        200: {
          content: {
            "application/json": components["schemas"]["AuthSuccessResponse"];
          };
        };
        /** @description Request is missing required information or is incorrectly formatted */
        400: {
          content: never;
        };
        /** @description User credentials are incorrect */
        401: {
          content: never;
        };
      };
    };
  };
  "/api/auth/refresh": {
    /** Auth token refresh */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthRefreshRequest"];
        };
      };
      responses: {
        /** @description Successful refresh request, grant new tokens */
        200: {
          content: {
            "application/json": components["schemas"]["AuthSuccessResponse"];
          };
        };
        /** @description Request is missing required information or is incorrectly formatted */
        400: {
          content: never;
        };
        /** @description Credentials incorrect or refresh token expired! */
        401: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @example {
     *   "username": "some text",
     *   "email": "some text",
     *   "created": 15532523,
     *   "hashed_password": {
     *     "hash_pass": "some text",
     *     "hash_salt": "some text"
     *   },
     *   "profile": {
     *     "full_name": "some text",
     *     "picture_link": "some text"
     *   },
     *   "id": "some text"
     * }
     */
    User: {
      /** @description Username of user */
      username: string;
      /** @description Email address of user */
      email: string;
      /** @description Timestamp of when user was created */
      created: number;
      /** @description Hash of user password for authentication */
      hashed_password: components["schemas"]["HashedPassword"];
      /** @description User profile */
      profile: components["schemas"]["UserProfile"];
      /** @description Unique user id (not technically necessary but helpful) */
      id: string;
    };
    /**
     * @example {
     *   "full_name": "some text",
     *   "picture_link": "some text"
     * }
     */
    UserProfile: {
      /** @description Full name of user */
      full_name: string;
      /** @description Link to profile photo */
      picture_link: string;
    };
    /**
     * @example {
     *   "id": "some text",
     *   "fountain_id": "some text",
     *   "user_id": "some text",
     *   "details": {
     *     "pressure": 2,
     *     "taste": 1,
     *     "temperature": 5
     *   }
     * }
     */
    FountainRating: {
      /** @description Unique id of fountain rating (technically not necessary but nice to have) */
      id: string;
      /** @description ID of fountain rating is for */
      fountain_id: string;
      /** @description ID of user who created rating */
      user_id: string;
      /** @description Details of fountain rating */
      details: components["schemas"]["FountainRatingDetails"];
    };
    /**
     * @example {
     *   "id": "some text",
     *   "f_or_b_id": "some text",
     *   "picture_link": "some text"
     * }
     */
    Picture: {
      /** @description Unique ID of picture */
      id: string;
      /** @description Fountain or bathroom ID picture is for */
      f_or_b_id: string;
      /** @description Link to picture */
      picture_link: string;
    };
    /**
     * @example {
     *   "id": "some text",
     *   "bathroom_id": "some text",
     *   "user_id": "some text",
     *   "details": {
     *     "cleanliness": 3,
     *     "decor": 3,
     *     "drying": 3,
     *     "privacy": 2,
     *     "washing": 5
     *   }
     * }
     */
    BathroomRating: {
      /** @description Unique id of bathroom rating */
      id: string;
      /** @description ID of bathroom rating is for */
      bathroom_id: string;
      /** @description ID of user who created bathroom rating */
      user_id: string;
      /** @description Details of bathroom rating */
      details: components["schemas"]["BathroomRatingDetails"];
    };
    /**
     * @description Set of login credentials
     * @example {
     *   "email": "some text",
     *   "password": "some text"
     * }
     */
    UserCredentials: {
      /** @description Email address of user */
      email: string;
      /** @description User's password */
      password: string;
    };
    /**
     * @description Secret credentials of trusted client
     * @example {
     *   "client_id": "some text",
     *   "client_secret": "some text"
     * }
     */
    ClientCredentials: {
      /** @description ID of client application */
      client_id: string;
      /** @description Secret of client application */
      client_secret: string;
    };
    /**
     * @description SHA256 hashed password (with salt)
     * @example {
     *   "hash_pass": "some text",
     *   "hash_salt": "some text"
     * }
     */
    HashedPassword: {
      /** @description Hashed password (SHA256) */
      hash_pass: string;
      /** @description Salt used for SHA256 hash */
      hash_salt: string;
    };
    /**
     * @description Identify a unique location (longitude and latitude)
     * @example {
     *   "longitude": 38.13,
     *   "latitude": 35.74
     * }
     */
    Location: {
      /** @description Longitude of location */
      longitude: number;
      /** @description Latitude of location */
      latitude: number;
    };
    /**
     * @description Information needed for signup request
     * @example {
     *   "username": "some text",
     *   "user_credentials": {
     *     "email": "some text",
     *     "password": "some text"
     *   },
     *   "client_credentials": {
     *     "client_id": "some text",
     *     "client_secret": "some text"
     *   }
     * }
     */
    SignupRequest: {
      /** @description New username for new user */
      username: string;
      /** @description Set of new credentials for new user */
      user_credentials: components["schemas"]["UserCredentials"];
      /** @description Set of client credentials */
      client_credentials: components["schemas"]["ClientCredentials"];
    };
    /**
     * @description Basic fountain information
     * @example {
     *   "id": "some text",
     *   "info": {
     *     "name": "some text",
     *     "bottle_filler": true,
     *     "location": {
     *       "longitude": 76.73,
     *       "latitude": 39.89
     *     }
     *   }
     * }
     */
    Fountain: {
      /** @description Unique ID of fountain */
      id: string;
      /** @description Fountain information */
      info: components["schemas"]["FountainInfo"];
    };
    /**
     * @example {
     *   "name": "some text",
     *   "bottle_filler": true,
     *   "location": {
     *     "longitude": 20.66,
     *     "latitude": 98.72
     *   }
     * }
     */
    FountainInfo: {
      /** @description Name for fountain */
      name: string;
      /** @description Whether or not the fountain features a dedicated bottle filler */
      bottle_filler: boolean;
      /** @description Location of fountain */
      location: components["schemas"]["Location"];
    };
    /**
     * @example {
     *   "name": "some text",
     *   "gender": "some text",
     *   "sanitary_products": true,
     *   "baby_changer": true,
     *   "location": {
     *     "longitude": 32.05,
     *     "latitude": 13.47
     *   }
     * }
     */
    BathroomInfo: {
      /** @description Name of bathroom */
      name: string;
      /** @description Gender/sex of bathroom */
      gender: string;
      /** @description Whether or not bathroom has sanitary products available (such as tampons and pads) */
      sanitary_products: boolean;
      /** @description Whether or not bathroom has a baby changer available */
      baby_changer: boolean;
      /** @description Location of bathroom */
      location: components["schemas"]["Location"];
    };
    /**
     * @description Bathroom
     * @example {
     *   "id": "some text",
     *   "info": {
     *     "name": "some text",
     *     "gender": "some text",
     *     "sanitary_products": true,
     *     "baby_changer": true,
     *     "location": {
     *       "longitude": 16.32,
     *       "latitude": 86.3
     *     }
     *   }
     * }
     */
    Bathroom: {
      /** @description Unique ID of bathroom */
      id: string;
      /** @description Info for bathroom */
      info: components["schemas"]["BathroomInfo"];
    };
    /**
     * @description Actual details of bathroom rating
     * @example {
     *   "cleanliness": 3,
     *   "decor": 1,
     *   "drying": 2,
     *   "privacy": 3,
     *   "washing": 5
     * }
     */
    BathroomRatingDetails: {
      /** @description Cleanliness rating of bathroom (0-5) */
      cleanliness: number;
      /** @description Decor rating of bathroom (0-5) */
      decor: number;
      /** @description Drying rating of bathroom (0-5) */
      drying: number;
      /** @description Privacy rating of bathroom (0-5) */
      privacy: number;
      /** @description Washing rating of bathroom (0-5) */
      washing: number;
    };
    /**
     * @description Details of fountain rating
     * @example {
     *   "pressure": 5,
     *   "taste": 4,
     *   "temperature": 1
     * }
     */
    FountainRatingDetails: {
      /** @description Pressure rating for fountain (0-5) */
      pressure: number;
      /** @description Taste rating for fountain (0-5) */
      taste: number;
      /** @description Temperature rating for fountain (0-5) */
      temperature: number;
    };
    /**
     * @description Tokens and token information returned after successful auth request
     * @example {
     *   "access_token": "some text",
     *   "refresh_token": "some text",
     *   "token_type": "some text",
     *   "expires": 39
     * }
     */
    AuthSuccessResponse: {
      /** @description Access token for user */
      access_token: string;
      /** @description Token to use to get a new token once access_token expires */
      refresh_token: string;
      /** @description Type of token (will be "Bearer") */
      token_type: string;
      /** @description Number of seconds that access_token is valid for */
      expires: number;
    };
    /**
     * @description Request format for refreshing auth access token
     * @example {
     *   "refresh_token": "some text",
     *   "expired_token": "some text"
     * }
     */
    AuthRefreshRequest: {
      /** @description Refresh token */
      refresh_token: string;
      /** @description Expired access token */
      expired_token: string;
    };
    /**
     * @description Body of POST request for authentication
     * @example {
     *   "user_credentials": {
     *     "email": "some text",
     *     "password": "some text"
     *   }
     * }
     */
    AuthRequest: {
      /** @description Credentials for user */
      user_credentials: components["schemas"]["UserCredentials"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
