import {
    ColumnType,
    Generated,
    Insertable,
    JSONColumnType,
    Selectable,
    Updateable
} from "kysely";

export interface Database {
    bathroom: BathroomTable,
    bathroomRating: BathroomRatingTable,
    fountain: FountainTable,
    fountainRating: FountainRatingTable,
    user: UserTable,
    picture: PictureTable
}

// Should only be used in the "Database" type above, never as a result of a query
export interface BathroomTable {
    // Keep in mind, columns that are generated by the database should be marked using the "Generated" type.
    // This way they are automatically made optional in inserts and updates.
    id: string,
    user_id: string,
}
